$(function(){
    $(".send").on("click",function(){
        cue("提醒","是否发送至经销商邮箱？")
        $("#yes").on("click",function(){
            $(".pop-box").hide()
            errLay("已发送至经销商邮箱")
        })
        $("#no").on("click",function(){
            $(".pop-box").hide()
        })
    })
    $(".weui-btn").on("click",function(){
        window.location.href="myOrder.html"
    })
})